[package]
name = "UrbanCalc"
version = "1.4.112"
edition = "2024"

[profile.release]
opt-level = 3    
lto = true       
codegen-units = 1 
strip = true    

[dependencies]
slint = "1.13.1"
chrono = "0.4"
once_cell = "1.17"
rdev = "0.5"


[build-dependencies]
slint-build = "1.8"
