import { Palette, HorizontalBox, VerticalBox, GridBox, Button } from "std-widgets.slint";

export global AppTheme {
    in property <color> background;
    in property <color> text;
}


component CalcButton inherits Rectangle {
    in-out property <string> text <=> txt.text;
    in-out property <image> icon <=> icon.source;
    in-out property <bool> compact: false;
    in-out property <color> button-color: #456;
    in-out property <color> hover-color: #39434D;
    in-out property <color> pressed-color: #162D42;
    in-out property <length> font_size: 15pt;
    in-out property <length> borders_radius: 15px;
    in-out property <color> text-color: white;

    callback clicked <=> touch.clicked;
    
    horizontal-stretch: compact ? 0 : 1;
    vertical-stretch: compact ? 0 : 1;
    min-width: max(txt.preferred-width, icon.width) + 16px;
    min-height: max(txt.preferred-width, icon.width) + 12px;
    preferred-width: max(txt.preferred-width, icon.width) + 16px;
    preferred-height: max(txt.preferred-width, icon.width) + 12px;
    border-radius: borders_radius;//root.height / 2;
    border-width: 1px;
    border-color: root.background.darker(25%);
    background: touch.pressed ? pressed-color : touch.has-hover ? hover-color : button-color;
    
    txt := Text {
        x: (parent.width - self.preferred-width)/2; 
        y: (parent.height - self.preferred-height)/2; 
        color: text-color;
        font-size: font_size;
        font-weight: 500;
    }
    
    icon := Image {
        x: (parent.width - self.width)/2; 
        y: (parent.height - self.height)/2; 
    }
    
    touch := TouchArea { }
}


export component MainWindow inherits Window {
    min-width: 325px;
    min-height: 500px;


    in property <image> backspace: @image-url("icons/backspace.svg");
    in property <image> divide: @image-url("icons/divide.svg");
    in property <image> clear: @image-url("icons/clear.svg");
    in property <image> multiple: @image-url("icons/multiple.svg");
    in property <image> minus: @image-url("icons/minus.svg");
    in property <image> plus: @image-url("icons/plus.svg");
    in property <image> equal: @image-url("icons/equal.svg");
    in property <image> dot: @image-url("icons/dot.svg");
    in property <image> nul: @image-url("icons/null.svg");
    in property <image> settings: @image-url("icons/settings.svg");

    VerticalBox {
        padding: 10px;

        HorizontalBox {
            padding: 0;
            CalcButton {
                icon: settings;
                compact: true;
                font_size: 12pt;
                borders_radius: 10px;
            }
            Rectangle {horizontal-stretch: 1;}

        }

            
        Text {
            text: "12+14";
            font-weight: 500;
            font-size: 30pt;
            vertical-alignment: top;
            horizontal-alignment: right;
        }

        Text {
            text: "26"; 
            font-weight: 500;
            font-size: 15pt;
            vertical-alignment: top;
            horizontal-alignment: right;
        }

        GridLayout {
            spacing: 5px;
            vertical-stretch: 1;
            CalcButton {text: "(";}
            CalcButton {text: ")";}
            CalcButton {icon: backspace;}
            CalcButton {icon: divide; button-color: #9D9065; hover-color: #766E56; pressed-color: #665621;}
            CalcButton {row: 1; text: "7";}
            CalcButton {text: "8";}
            CalcButton {text: "9";}
            CalcButton {icon: multiple; button-color: #9D9065; hover-color: #766E56; pressed-color: #665621;}
            CalcButton {row: 2; text: "4";}
            CalcButton {text: "5";}
            CalcButton {text: "6";}
            CalcButton {icon: minus; button-color: #9D9065; hover-color: #766E56; pressed-color: #665621;}
            CalcButton {row: 3; text: "1";}
            CalcButton {text: "2";}
            CalcButton {text: "3";}
            CalcButton {icon: plus; button-color: #9D9065; hover-color: #766E56; pressed-color: #665621;}
            CalcButton {row: 4; icon: clear;}
            CalcButton {text: "0";}
            CalcButton {icon: dot;}
            CalcButton {icon: equal; button-color: #4E4C6E; hover-color: #403F52; pressed-color: #1B1947;}

        }
    }

}
